#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=MT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=15:00:00
#SBATCH --output=slurm_output_%A.out
#SBATCH --exclude=gcn45

module purge
module load 2022
module load Anaconda3/2022.05

source activate thesis

SUBJECT=5

ROI1="OFA"
ROI2="FFA-1"
python run_all_exp2.py --subject $SUBJECT --roi1 $ROI1 --roi2 $ROI2 --data_root "/gpfs/work5/0/gusr53691/data/" --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/"  --output_dir "/gpfs/work5/0/gusr53691/data/exp2_outputs/"

ROI1="EBA"
ROI2="FBA-1"
python run_all_exp2.py --subject $SUBJECT --roi1 $ROI1 --roi2 $ROI2 --data_root "/gpfs/work5/0/gusr53691/data/" --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/"  --output_dir "/gpfs/work5/0/gusr53691/data/exp2_outputs/"

ROI1="OPA"
ROI2="PPA"
python run_all_exp2.py --subject $SUBJECT --roi1 $ROI1 --roi2 $ROI2 --data_root "/gpfs/work5/0/gusr53691/data/" --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/"  --output_dir "/gpfs/work5/0/gusr53691/data/exp2_outputs/"

ROI1="RSC"
ROI2="PPA"
python run_all_exp2.py --subject $SUBJECT --roi1 $ROI1 --roi2 $ROI2 --data_root "/gpfs/work5/0/gusr53691/data/" --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/"  --output_dir "/gpfs/work5/0/gusr53691/data/exp2_outputs/"

ROI1="OWFA"
ROI2="VWFA-1"
python run_all_exp2.py --subject $SUBJECT --roi1 $ROI1 --roi2 $ROI2 --data_root "/gpfs/work5/0/gusr53691/data/" --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/"  --output_dir "/gpfs/work5/0/gusr53691/data/exp2_outputs/"