#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=MT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=10:00:00
#SBATCH --mem=120000M
#SBATCH --output=slurm_output_%A.out
#SBATCH --exclude=gcn45

module purge
module load 2022
module load Anaconda3/2022.05

source activate thesis

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 1 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 1 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 2 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 2 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 3 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 3 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 4 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 4 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 5 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 5 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 6 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 6 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 7 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 7 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear

python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 8 --batch_size 64 --roi "all" --hemisphere "right" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear
python run_train_encoder.py --dataset_dir "/gpfs/work5/0/gusr53691/data/NSD/" --subject 8 --batch_size 64 --roi "all" --hemisphere "left" --max_epochs 10 --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --clip_linear