#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=MT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=15:00:00
#SBATCH --mem=120000M
#SBATCH --output=slurm_output_%A.out
#SBATCH --exclude=gcn45

module purge
module load 2022
module load Anaconda3/2022.05

source activate thesis

python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 1 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 2 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 3 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 4 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 5 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 6 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 7 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"
python run_gen_part1.py --dataset_root "/gpfs/work5/0/gusr53691/data/NSD/" --ckpt_dir "/gpfs/work5/0/gusr53691/data/checkpoints/" --subject 8 --roi "PPA" --hemisphere "right" --output_dir "/gpfs/work5/0/gusr53691/data/part1_outputs/"